# Generated by Django 5.1.3 on 2024-12-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designgallery',
            name='image',
            field=models.ImageField(max_length=255, upload_to='designs/'),
        ),
    ]
