# Generated by Django 5.1.3 on 2024-12-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
