# Generated by Django 5.1.4 on 2024-12-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_appointment_is_paid_appointment_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(help_text='Durasi layanan dalam format HH:MM:SS'),
        ),
    ]
