# Generated by Django 5.1.4 on 2024-12-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_alter_service_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(help_text='Duration of service (HH:MM:SS)'),
        ),
    ]
